services:

  go-nginx-server:
    image: nginx
    build:
      context: .
      dockerfile: ./.nginx/Dockerfile
    #volumes:
    #  - type: bind
    #    source: ./.nginx/nginx.conf
    #    target: /etc/nginx/conf.d/default.conf
    #    read_only: true
    ports:
      - 80:80
    depends_on:
      - go-backend-server

  go-backend-server:
    build:
      context: backend # Видимо, переходим в эту папку, и работаем в ней
      dockerfile: Dockerfile
    ports: # The format is "host_port:container_port", т.е. "порт машины:порт контейнера"
      - "8888:8888"
