services:
  go-nginx-test-server:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - type: bind
    #    source: ./.nginx/nginx.conf
    #    target: /etc/nginx/conf.d/default.conf
    #    read_only: true
    ports:
      - 8080:80
